CREATE TABLE [dbo].[core_systemsettings] (
    [key]   VARCHAR (100) NOT NULL,
    [value] VARCHAR (100) NOT NULL,
    PRIMARY KEY CLUSTERED ([key] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

