ALTER TABLE [dbo].[core_systemsettings]
    ADD CONSTRAINT [PK_core_systemsettings] PRIMARY KEY CLUSTERED ([key] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

