//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace StudentMonitoringSystem.Entities
{
    [Serializable]
    public partial class core_province: BaseObject
    {
        #region Primitive Properties
    
        public virtual int id
        {
            get;
            set;
        }
    
        public virtual string name
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<core_city> core_city
        {
            get
            {
                if (_core_city == null)
                {
                    var newCollection = new FixupCollection<core_city>();
                    newCollection.CollectionChanged += Fixupcore_city;
                    _core_city = newCollection;
                }
                return _core_city;
            }
            set
            {
                if (!ReferenceEquals(_core_city, value))
                {
                    var previousValue = _core_city as FixupCollection<core_city>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupcore_city;
                    }
                    _core_city = value;
                    var newValue = value as FixupCollection<core_city>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupcore_city;
                    }
                }
            }
        }
        private ICollection<core_city> _core_city;

        #endregion
        #region Association Fixup
    
        private void Fixupcore_city(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (core_city item in e.NewItems)
                {
                    item.core_province = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (core_city item in e.OldItems)
                {
                    if (ReferenceEquals(item.core_province, this))
                    {
                        item.core_province = null;
                    }
                }
            }
        }

        #endregion
    }
}
