//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace StudentMonitoringSystem.Entities
{
    [Serializable]
    public partial class core_guardian: BaseObject
    {
        #region Primitive Properties
    
        public virtual int id
        {
            get;
            set;
        }
    
        public virtual string number
        {
            get;
            set;
        }
    
        public virtual string emailaddress
        {
            get;
            set;
        }
    
        public virtual string relationship
        {
            get;
            set;
        }
    
        public virtual int student_id
        {
            get { return _student_id; }
            set
            {
                if (_student_id != value)
                {
                    if (core_student != null && core_student.id != value)
                    {
                        core_student = null;
                    }
                    _student_id = value;
                }
            }
        }
        private int _student_id;
    
        public virtual string note
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual core_student core_student
        {
            get { return _core_student; }
            set
            {
                if (!ReferenceEquals(_core_student, value))
                {
                    var previousValue = _core_student;
                    _core_student = value;
                    Fixupcore_student(previousValue);
                }
            }
        }
        private core_student _core_student;

        #endregion
        #region Association Fixup
    
        private void Fixupcore_student(core_student previousValue)
        {
            if (previousValue != null && previousValue.core_guardian.Contains(this))
            {
                previousValue.core_guardian.Remove(this);
            }
    
            if (core_student != null)
            {
                if (!core_student.core_guardian.Contains(this))
                {
                    core_student.core_guardian.Add(this);
                }
                if (student_id != core_student.id)
                {
                    student_id = core_student.id;
                }
            }
        }

        #endregion
    }
}
