//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace StudentMonitoringSystem.Entities
{
    [Serializable]
    public partial class emp_contact: BaseObject
    {
        #region Primitive Properties
    
        public virtual int id
        {
            get;
            set;
        }
    
        public virtual string number
        {
            get;
            set;
        }
    
        public virtual string emailaddress
        {
            get;
            set;
        }
    
        public virtual string remarks
        {
            get;
            set;
        }
    
        public virtual int employee_id
        {
            get { return _employee_id; }
            set
            {
                if (_employee_id != value)
                {
                    if (emp_employee != null && emp_employee.id != value)
                    {
                        emp_employee = null;
                    }
                    _employee_id = value;
                }
            }
        }
        private int _employee_id;

        #endregion
        #region Navigation Properties
    
        public virtual emp_employee emp_employee
        {
            get { return _emp_employee; }
            set
            {
                if (!ReferenceEquals(_emp_employee, value))
                {
                    var previousValue = _emp_employee;
                    _emp_employee = value;
                    Fixupemp_employee(previousValue);
                }
            }
        }
        private emp_employee _emp_employee;

        #endregion
        #region Association Fixup
    
        private void Fixupemp_employee(emp_employee previousValue)
        {
            if (previousValue != null && previousValue.emp_contact.Contains(this))
            {
                previousValue.emp_contact.Remove(this);
            }
    
            if (emp_employee != null)
            {
                if (!emp_employee.emp_contact.Contains(this))
                {
                    emp_employee.emp_contact.Add(this);
                }
                if (employee_id != emp_employee.id)
                {
                    employee_id = emp_employee.id;
                }
            }
        }

        #endregion
    }
}
