//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace StudentMonitoringSystem.Entities
{
    [Serializable]
    public partial class enroll_course: BaseObject
    {
        #region Primitive Properties
    
        public override int id
        {
            get;
            set;
        }
    
        public  string name
        {
            get;
            set;
        }
    
        public  string code
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<enroll_section> enroll_section
        {
            get
            {
                if (_enroll_section == null)
                {
                    var newCollection = new FixupCollection<enroll_section>();
                    newCollection.CollectionChanged += Fixupenroll_section;
                    _enroll_section = newCollection;
                }
                return _enroll_section;
            }
            set
            {
                if (!ReferenceEquals(_enroll_section, value))
                {
                    var previousValue = _enroll_section as FixupCollection<enroll_section>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupenroll_section;
                    }
                    _enroll_section = value;
                    var newValue = value as FixupCollection<enroll_section>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupenroll_section;
                    }
                }
            }
        }
        private ICollection<enroll_section> _enroll_section;
    
        public virtual ICollection<enroll_schedule> enroll_schedule
        {
            get
            {
                if (_enroll_schedule == null)
                {
                    var newCollection = new FixupCollection<enroll_schedule>();
                    newCollection.CollectionChanged += Fixupenroll_schedule;
                    _enroll_schedule = newCollection;
                }
                return _enroll_schedule;
            }
            set
            {
                if (!ReferenceEquals(_enroll_schedule, value))
                {
                    var previousValue = _enroll_schedule as FixupCollection<enroll_schedule>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupenroll_schedule;
                    }
                    _enroll_schedule = value;
                    var newValue = value as FixupCollection<enroll_schedule>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupenroll_schedule;
                    }
                }
            }
        }
        private ICollection<enroll_schedule> _enroll_schedule;

        #endregion
        #region Association Fixup
    
        private void Fixupenroll_section(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (enroll_section item in e.NewItems)
                {
                    item.enroll_course = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (enroll_section item in e.OldItems)
                {
                    if (ReferenceEquals(item.enroll_course, this))
                    {
                        item.enroll_course = null;
                    }
                }
            }
        }
    
        private void Fixupenroll_schedule(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (enroll_schedule item in e.NewItems)
                {
                    item.enroll_course = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (enroll_schedule item in e.OldItems)
                {
                    if (ReferenceEquals(item.enroll_course, this))
                    {
                        item.enroll_course = null;
                    }
                }
            }
        }

        #endregion
    }
}
