//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace StudentMonitoringSystem.Entities
{
    [Serializable]
    public partial class enroll_semester: BaseObject
    {
        #region Primitive Properties
    
        public override int id
        {
            get;
            set;
        }
    
        public  string name
        {
            get;
            set;
        }
    
        public  string note
        {
            get;
            set;
        }
    
        public  int recordorder
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<enroll_enrolledyear> enroll_enrolledyear
        {
            get
            {
                if (_enroll_enrolledyear == null)
                {
                    var newCollection = new FixupCollection<enroll_enrolledyear>();
                    newCollection.CollectionChanged += Fixupenroll_enrolledyear;
                    _enroll_enrolledyear = newCollection;
                }
                return _enroll_enrolledyear;
            }
            set
            {
                if (!ReferenceEquals(_enroll_enrolledyear, value))
                {
                    var previousValue = _enroll_enrolledyear as FixupCollection<enroll_enrolledyear>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupenroll_enrolledyear;
                    }
                    _enroll_enrolledyear = value;
                    var newValue = value as FixupCollection<enroll_enrolledyear>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupenroll_enrolledyear;
                    }
                }
            }
        }
        private ICollection<enroll_enrolledyear> _enroll_enrolledyear;

        #endregion
        #region Association Fixup
    
        private void Fixupenroll_enrolledyear(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (enroll_enrolledyear item in e.NewItems)
                {
                    item.enroll_semester = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (enroll_enrolledyear item in e.OldItems)
                {
                    if (ReferenceEquals(item.enroll_semester, this))
                    {
                        item.enroll_semester = null;
                    }
                }
            }
        }

        #endregion
    }
}
