//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace StudentMonitoringSystem.Entities
{
    [Serializable]
    public partial class enroll_enrolledyear: BaseObject
    {
        #region Primitive Properties
    
        public override int id
        {
            get;
            set;
        }
    
        public  int level_id
        {
            get { return _level_id; }
            set
            {
                if (_level_id != value)
                {
                    if (enroll_level != null && enroll_level.id != value)
                    {
                        enroll_level = null;
                    }
                    _level_id = value;
                }
            }
        }
        private int _level_id;
    
        public  int schoolyear_id
        {
            get { return _schoolyear_id; }
            set
            {
                if (_schoolyear_id != value)
                {
                    if (enroll_schoolyear != null && enroll_schoolyear.id != value)
                    {
                        enroll_schoolyear = null;
                    }
                    _schoolyear_id = value;
                }
            }
        }
        private int _schoolyear_id;
    
        public  int course_id
        {
            get { return _course_id; }
            set
            {
                if (_course_id != value)
                {
                    if (enroll_course != null && enroll_course.id != value)
                    {
                        enroll_course = null;
                    }
                    _course_id = value;
                }
            }
        }
        private int _course_id;
    
        public  int section_id
        {
            get { return _section_id; }
            set
            {
                if (_section_id != value)
                {
                    if (enroll_section != null && enroll_section.id != value)
                    {
                        enroll_section = null;
                    }
                    _section_id = value;
                }
            }
        }
        private int _section_id;
    
        public  string note
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual enroll_course enroll_course
        {
            get { return _enroll_course; }
            set
            {
                if (!ReferenceEquals(_enroll_course, value))
                {
                    var previousValue = _enroll_course;
                    _enroll_course = value;
                    Fixupenroll_course(previousValue);
                }
            }
        }
        private enroll_course _enroll_course;
    
        public virtual enroll_level enroll_level
        {
            get { return _enroll_level; }
            set
            {
                if (!ReferenceEquals(_enroll_level, value))
                {
                    var previousValue = _enroll_level;
                    _enroll_level = value;
                    Fixupenroll_level(previousValue);
                }
            }
        }
        private enroll_level _enroll_level;
    
        public virtual enroll_schoolyear enroll_schoolyear
        {
            get { return _enroll_schoolyear; }
            set
            {
                if (!ReferenceEquals(_enroll_schoolyear, value))
                {
                    var previousValue = _enroll_schoolyear;
                    _enroll_schoolyear = value;
                    Fixupenroll_schoolyear(previousValue);
                }
            }
        }
        private enroll_schoolyear _enroll_schoolyear;
    
        public virtual enroll_section enroll_section
        {
            get { return _enroll_section; }
            set
            {
                if (!ReferenceEquals(_enroll_section, value))
                {
                    var previousValue = _enroll_section;
                    _enroll_section = value;
                    Fixupenroll_section(previousValue);
                }
            }
        }
        private enroll_section _enroll_section;

        #endregion
        #region Association Fixup
    
        private void Fixupenroll_course(enroll_course previousValue)
        {
            if (previousValue != null && previousValue.enroll_enrolledyear.Contains(this))
            {
                previousValue.enroll_enrolledyear.Remove(this);
            }
    
            if (enroll_course != null)
            {
                if (!enroll_course.enroll_enrolledyear.Contains(this))
                {
                    enroll_course.enroll_enrolledyear.Add(this);
                }
                if (course_id != enroll_course.id)
                {
                    course_id = enroll_course.id;
                }
            }
        }
    
        private void Fixupenroll_level(enroll_level previousValue)
        {
            if (previousValue != null && previousValue.enroll_enrolledyear.Contains(this))
            {
                previousValue.enroll_enrolledyear.Remove(this);
            }
    
            if (enroll_level != null)
            {
                if (!enroll_level.enroll_enrolledyear.Contains(this))
                {
                    enroll_level.enroll_enrolledyear.Add(this);
                }
                if (level_id != enroll_level.id)
                {
                    level_id = enroll_level.id;
                }
            }
        }
    
        private void Fixupenroll_schoolyear(enroll_schoolyear previousValue)
        {
            if (previousValue != null && previousValue.enroll_enrolledyear.Contains(this))
            {
                previousValue.enroll_enrolledyear.Remove(this);
            }
    
            if (enroll_schoolyear != null)
            {
                if (!enroll_schoolyear.enroll_enrolledyear.Contains(this))
                {
                    enroll_schoolyear.enroll_enrolledyear.Add(this);
                }
                if (schoolyear_id != enroll_schoolyear.id)
                {
                    schoolyear_id = enroll_schoolyear.id;
                }
            }
        }
    
        private void Fixupenroll_section(enroll_section previousValue)
        {
            if (previousValue != null && previousValue.enroll_enrolledyear.Contains(this))
            {
                previousValue.enroll_enrolledyear.Remove(this);
            }
    
            if (enroll_section != null)
            {
                if (!enroll_section.enroll_enrolledyear.Contains(this))
                {
                    enroll_section.enroll_enrolledyear.Add(this);
                }
                if (section_id != enroll_section.id)
                {
                    section_id = enroll_section.id;
                }
            }
        }

        #endregion
    }
}
