//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace StudentMonitoringSystem.Entities
{
    [Serializable]
    public partial class log_entrybook: BaseObject
    {
        #region Primitive Properties
    
        public virtual int id
        {
            get;
            set;
        }
    
        public virtual string rfid
        {
            get;
            set;
        }
    
        public virtual System.DateTime timein
        {
            get;
            set;
        }
    
        public virtual System.DateTime timeout
        {
            get;
            set;
        }
    
        public virtual System.DateTime datecreated
        {
            get;
            set;
        }
    
        public virtual bool @override
        {
            get;
            set;
        }

        #endregion
    }
}
