//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace StudentMonitoringSystem.Entities
{
    [Serializable]
    public partial class sms_networkprovider: BaseObject
    {
        #region Primitive Properties
    
        public override int id
        {
            get;
            set;
        }
    
        public  string name
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<sms_networkprovidercode> sms_networkprovidercode
        {
            get
            {
                if (_sms_networkprovidercode == null)
                {
                    var newCollection = new FixupCollection<sms_networkprovidercode>();
                    newCollection.CollectionChanged += Fixupsms_networkprovidercode;
                    _sms_networkprovidercode = newCollection;
                }
                return _sms_networkprovidercode;
            }
            set
            {
                if (!ReferenceEquals(_sms_networkprovidercode, value))
                {
                    var previousValue = _sms_networkprovidercode as FixupCollection<sms_networkprovidercode>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupsms_networkprovidercode;
                    }
                    _sms_networkprovidercode = value;
                    var newValue = value as FixupCollection<sms_networkprovidercode>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupsms_networkprovidercode;
                    }
                }
            }
        }
        private ICollection<sms_networkprovidercode> _sms_networkprovidercode;

        #endregion
        #region Association Fixup
    
        private void Fixupsms_networkprovidercode(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (sms_networkprovidercode item in e.NewItems)
                {
                    item.sms_networkprovider = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (sms_networkprovidercode item in e.OldItems)
                {
                    if (ReferenceEquals(item.sms_networkprovider, this))
                    {
                        item.sms_networkprovider = null;
                    }
                }
            }
        }

        #endregion
    }
}
