//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace StudentMonitoringSystem.Entities
{
    [Serializable]
    public partial class sms_inbox: BaseObject
    {
        #region Primitive Properties
    
        public override int id
        {
            get;
            set;
        }
    
        public  string number
        {
            get;
            set;
        }
    
        public  string message
        {
            get;
            set;
        }
    
        public  System.DateTime datecreated
        {
            get;
            set;
        }
    
        public  int status_id
        {
            get { return _status_id; }
            set
            {
                if (_status_id != value)
                {
                    if (sms_status != null && sms_status.id != value)
                    {
                        sms_status = null;
                    }
                    _status_id = value;
                }
            }
        }
        private int _status_id;

        #endregion
        #region Navigation Properties
    
        public virtual sms_status sms_status
        {
            get { return _sms_status; }
            set
            {
                if (!ReferenceEquals(_sms_status, value))
                {
                    var previousValue = _sms_status;
                    _sms_status = value;
                    Fixupsms_status(previousValue);
                }
            }
        }
        private sms_status _sms_status;

        #endregion
        #region Association Fixup
    
        private void Fixupsms_status(sms_status previousValue)
        {
            if (previousValue != null && previousValue.sms_inbox.Contains(this))
            {
                previousValue.sms_inbox.Remove(this);
            }
    
            if (sms_status != null)
            {
                if (!sms_status.sms_inbox.Contains(this))
                {
                    sms_status.sms_inbox.Add(this);
                }
                if (status_id != sms_status.id)
                {
                    status_id = sms_status.id;
                }
            }
        }

        #endregion
    }
}
