//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace StudentMonitoringSystem.Entities
{
    [Serializable]
    public partial class vstudentinfo: BaseObject
    {
        #region Primitive Properties
    
        public override int id
        {
            get;
            set;
        }
    
        public  string number
        {
            get;
            set;
        }
    
        public  string firstname
        {
            get;
            set;
        }
    
        public  string middlename
        {
            get;
            set;
        }
    
        public  string lastname
        {
            get;
            set;
        }
    
        public  System.DateTime dateofbirth
        {
            get;
            set;
        }
    
        public  string picture
        {
            get;
            set;
        }
    
        public  int gender_id
        {
            get;
            set;
        }
    
        public  int civilstatus_id
        {
            get;
            set;
        }
    
        public  string civilstatus_name
        {
            get;
            set;
        }
    
        public  string citizenship
        {
            get;
            set;
        }
    
        public  string street
        {
            get;
            set;
        }
    
        public  int barangay_id
        {
            get;
            set;
        }
    
        public  string note
        {
            get;
            set;
        }
    
        public  string gender_name
        {
            get;
            set;
        }
    
        public  string barangay_name
        {
            get;
            set;
        }
    
        public  int city_id
        {
            get;
            set;
        }
    
        public  string city_name
        {
            get;
            set;
        }
    
        public  int province_id
        {
            get;
            set;
        }
    
        public  string province_name
        {
            get;
            set;
        }
    
        public  string fathername
        {
            get;
            set;
        }
    
        public  string fatheroccupation
        {
            get;
            set;
        }
    
        public  string fathercontactnumber
        {
            get;
            set;
        }
    
        public  string fatheraddress
        {
            get;
            set;
        }
    
        public  string mothername
        {
            get;
            set;
        }
    
        public  string motheroccupation
        {
            get;
            set;
        }
    
        public  string mothercontactnumber
        {
            get;
            set;
        }
    
        public  string motheraddress
        {
            get;
            set;
        }

        #endregion
    }
}
