//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace StudentMonitoringSystem.Entities
{
    [Serializable]
    public partial class vstudentinfo: BaseObject
    {
        #region Primitive Properties
    
        public virtual int id
        {
            get;
            set;
        }
    
        public virtual string number
        {
            get;
            set;
        }
    
        public virtual string firstname
        {
            get;
            set;
        }
    
        public virtual string middlename
        {
            get;
            set;
        }
    
        public virtual string lastname
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> dateofbirth
        {
            get;
            set;
        }
    
        public virtual string citizenship
        {
            get;
            set;
        }
    
        public virtual int gender_id
        {
            get;
            set;
        }
    
        public virtual string gender
        {
            get;
            set;
        }
    
        public virtual int civilstatus_id
        {
            get;
            set;
        }
    
        public virtual string civilstatus
        {
            get;
            set;
        }

        #endregion
    }
}
